# Example report_config.yaml

report_config:
  # Weights for different tests (by rule_id) - used for weighted scoring
  test_weights:
    audit_completeness_check: 0.25
    review_timeliness_check: 0.20
    documentation_quality_check: 0.15
    risk_assessment_check: 0.20
    control_effectiveness_check: 0.20
    # Default weight for tests not specified: 0.10

  # Compliance rate ranges mapped to scores (1-5 scale)
  score_mapping:
    "0.95-1.00": 5
    "0.85-0.94": 4
    "0.70-0.84": 3
    "0.50-0.69": 2
    "0.00-0.49": 1

  # Human-readable labels for each score
  rating_labels:
    5: "Satisfactory"
    4: "Meets Expectations"
    3: "Requires Attention"
    2: "Needs Improvement"
    1: "Unsatisfactory"

  # Detailed explanations for specific rules
  rule_explanations:
    audit_completeness_check: >
      This rule validates that all required sections of the audit have been completed and signed off.
      The formula checks for non-null values in the signoff and completion date fields, as well as
      ensuring that all required documentation is attached.

    review_timeliness_check: >
      This rule verifies that reviews were completed within the required timeframe.
      It compares the 'due_date' field with the 'completion_date' field to calculate delays.
      Reviews completed on or before the due date pass validation.

    documentation_quality_check: >
      This rule assesses the quality of documentation by checking that all required evidence fields
      are populated with substantive content (not just placeholders or minimal entries).
      It validates both the presence and minimum quality criteria of documentation.

    risk_assessment_check: >
      This rule validates that risk assessments include all required components:
      (1) inherent risk rating, (2) control effectiveness rating, (3) residual risk calculation,
      and (4) appropriate risk mitigation strategies for high-risk items.

    control_effectiveness_check: >
      This rule evaluates whether control testing results are properly documented and whether
      controls rated as ineffective have appropriate remediation plans with reasonable timelines.

  # Format specifications for special columns
  column_formats:
    percentage: '0.0%'
    score: '0.0'
    currency: '$#,##0.00'
    date: 'yyyy-mm-dd'

  # Display options for reports
  display_options:
    max_failures_per_rule: 1000
    show_formula_on_sheets: true
    enable_conditional_formatting: true
    include_explanation_section: true
    show_intermediate_calculations: true